# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': '投稿',
                'verbose_name': '投稿',
            },
        ),
    ]
